Repository DUNE-DAQ/readoutlibs, pull requests merged in 2022-10, with the labels that each got.

#65 fixing reaout window logic
  include/readoutlibs/models/detail/DefaultRequestHandlerModel.hxx
Labels: feature

#68 Pipeline name fix
  include/readoutlibs/models/detail/TaskRawDataProcessorModel.hxx
Labels: bug

#71 Shorter name for 15 char limit
  include/readoutlibs/models/detail/TaskRawDataProcessorModel.hxx
Labels: enhancement
