Repository DUNE-DAQ/readoutlibs, pull requests merged in 2024-03, with the labels that each got.

#160 Improved the Tardy-TP warning message and added suppression of it at start-run
  include/readoutlibs/ReadoutIssues.hpp
  include/readoutlibs/models/DefaultRequestHandlerModel.hpp
  include/readoutlibs/models/detail/ReadoutModel.hxx
  schema/readoutlibs/readoutconfig.jsonnet
Labels: miscellaneous deliverable

#158 Add TPG configuration parameters
  schema/readoutlibs/readoutconfig.jsonnet
Labels: enhancement, miscellaneous deliverable

#163 Change definitions of the Info
  schema/readoutlibs/readoutinfo.jsonnet
Labels: miscellaneous deliverable

#164 Roland sipos/data move cb registry
  include/readoutlibs/DataMoveCallbackRegistry.hpp
  include/readoutlibs/detail/DataMoveCallbackRegistry.hxx
  include/readoutlibs/models/ReadoutModel.hpp
  include/readoutlibs/models/detail/ReadoutModel.hxx
  scripts/readout-affinity.py
  src/DataMoveCallbackRegistry.cpp
Labels: enhancement, feature
